### ISSUE TITLE
Invalid localDate value to send to the db

### ISSUE THREAD

**Issue by guzmanf** [juanluispaz/ts-sql-query#105]
hello friends

in postgresql, how to resolve "Invalid localDate value to send to the db: 2023-5-20"
...help, advice

regards

**Comment by juanluispaz** [comment]
Hi,

Please, always include the database name you are using (PostgreSQL, Oracle, etc.) and, if possible, a small example.

It sounds like you are bypassing the typescript type validations; localDate expects a Date object, but you are providing the string "2023-5-20". In this case, the type indicated by TypeScript and the type received in JavaScript is not matching.

If you want to use date as string, you should use a "customComparable" field in the table definition.

Let me know if this helps you.

**Comment by guzmanf** [comment]
Juan....
muchas gracias efectivamente era el tipo de dato que no estaba validando, error de principiante.
salu2
