### ISSUE TITLE
Oracle Procedure Out Params

### ISSUE THREAD

**Issue by platzhersh** [juanluispaz/ts-sql-query#106]
Hello there,

it's me again, with another Oracle specific (?) feature request.

Oracle supports IN and OUT params for procedure calls. OUT params being params that will be populated with information during the procedure call.

https://www.tutorialspoint.com/plsql/plsql_procedures.htm#:~:text=An%20IN%20OUT%20parameter%20passes,must%20be%20assigned%20a%20value.

Example for a procedure call with an OUT param:

```sql
DECLARE
msg VARCHAR2(4000);
BEGIN
PR_DEL_E2EUSER('T_XYZ', msg);
dbms_output.put_line(msg);
END;
```

example code of the previously called procedure:

```sql
create PROCEDURE PR_DEL_E2EUSER(
                         P_PATNR IN VARCHAR2,                
                         P_RESMSG OUT VARCHAR2) IS

BEGIN

-- ...DO SOMETHING...
P_RESMSG:= 'some success message';
commit;

EXCEPTION
WHEN OTHERS THEN
    rollback;
    P_RESMSG:= 'some error message';


END PR_DEL_E2EUSER;
/

```

If I haven't missed anything, I think a procedure call like this is not yet possible in ts-sql-query?

**Comment by juanluispaz** [comment]
Hi, 

ts-sql-query uses output parameters in several places (in Oracle), but right now, there is no way to call a procedure with output parameters; said that, ts-sql-query always offers you a way to do operations not supported by the library. In this case, we will need to go closer to the database connection. You can do the following in your DBConnection: 

```ts
class DBConnection extends OracleConnection<'DBConnection'> {
    deleteUserReturningObjectWithMessage(userId: string): Promise<{message: string}> {
        const queryRunner = this.queryRunner
        const params: any[] = []
        return queryRunner.executeUpdateReturningOneRow(`begin PR_DEL_E2EUSER(${queryRunner.addParam(params, userId)}, ${queryRunner.addOutParam(params, 'message')}); end;`, params)
    }
    deleteUserReturningMessage(userId: string): Promise<string> {
        const queryRunner = this.queryRunner
        const params: any[] = []
        return queryRunner.executeUpdateReturningOneColumnOneRow(`begin PR_DEL_E2EUSER(${queryRunner.addParam(params, userId)}, ${queryRunner.addOutParam(params, 'message')}); end;`, params)
    }
    deleteUserLowLevel(userId: string): Promise<string> {
        return this.queryRunner.execute(async (connection) => {
            const oracleConnection = connection as oracledb.Connection
            const result = await oracleConnection.execute('begin PR_DEL_E2EUSER(:id, :message); end;', {id: userId, message: {dir: oracledb.BIND_OUT}})
            return (result.outBinds as any).message
        })
    }
}
```

Then you can call it in this way:

```ts
        let message: string
        message = await connection.deleteUserReturningMessage('user_id')
        assertEquals(message, 'some success message')

        message = (await connection.deleteUserReturningObjectWithMessage('user_id')).message
        assertEquals(message, 'some success message')

        message = await connection.deleteUserLowLevel('user_id')
        assertEquals(message, 'some success message')
```

I'm putting here three ways to call that procedure you mentioned; the first two use the low-level query interface. Update queries use out parameters; that is why I use that; these functions look inside the output parameters of the requested value. The second param to `addOutParam` is a name for the output param in the result, but when you use the one-column variant, the value is extracted and returned, then you will not see that in the result. I should add two new functions to the query runner that make explicit you are executing a procedure, something like `executeProcedureReturningOneRow` and `executeProcedureReturningOneColumnOneRow`.

The third variant allows you to go directly to the Oracle connection object and perform your query. Be aware when you go in this way, any interceptor (like a logger) will not see the query.

How to make a high-level API to call procedures that return output params (there is already one for procedures without output params) is a good question. Let me know if you have some ideas.

**Comment by juanluispaz** [comment]
I will keep it as in the example; in that way, the query runner calls represent the intention of the action in the database.

Let me know any feedback.
