### ISSUE TITLE
Add QueryRunner for sqlite3 wasm implementation

### ISSUE THREAD

**Issue by melink14** [juanluispaz/ts-sql-query#107]
SQLite now officially supports a build for use in WASM-capable browsers. It has a couple different APIs but they it seems like it should be fairly simple to create a QueryRunner for them and gaining all the benefits of ts-sql-query in the browser.

Ref: https://sqlite.org/wasm/doc/trunk/index.md

Let me know if that's reasonable or if there's anything I can do to help.

**Comment by juanluispaz** [comment]
Good!!!

I will add support to it.

I think there will appear two different query runners:

- **Sqlite3WasmOO1QueryRunner**: using the [object oriented 1 API](https://sqlite.org/wasm/doc/trunk/api-oo1.md), this can optionally support [synchronous queries](https://ts-sql-query.readthedocs.io/en/stable/advanced-usage/#synchronous-query-runners) in the same way [BetterSqlite3QueryRunner](https://ts-sql-query.readthedocs.io/en/stable/query-runners/recommended-query-runners/#better-sqlite3) support it.
- **Sqlite3WasmWorker1PromiserQueryRunner**:  using the [worker 1 promiser API](https://sqlite.org/wasm/doc/trunk/api-worker1.md); this always will run asynchronously.

What do you think? Am I leaving something behind?

**Comment by melink14** [comment]
That seems good to me! (I don't think there would be any reason to support the C API in additon to the OO1 api afaict)

Thanks for the fast response!

**Comment by juanluispaz** [comment]
I'm waiting for https://github.com/tomayac/sqlite-wasm/issues/1 be fixed to add support to `@sqlite.org/sqlite-wasm`

**Comment by juanluispaz** [comment]
Released ts-sql-query 1.57.0 implementing Sqlite3WasmOO1QueryRunner

**Comment by melink14** [comment]
Thanks @juanluispaz for the work here. I hope to try it out soon!
