### ISSUE TITLE
Connection-string for mssql. 

### ISSUE THREAD

**Issue by runar-rkmedia** [juanluispaz/ts-sql-query#109]
This may be a dumb question, but I could not find any information about it. I am attempting to use this with mssql, but could not find the approprate connection-string to use, especially where to put the instance-name.

For instance, with usql, the connection-string is:

```
mssql://User:Password@hostname:port/instance
```
with [node-mssql](https://tediousjs.github.io/node-mssql/#general-same-for-all-drivers), I use this:

```
const sqlConfig = {
  user: 'User',
  password: 'Password',
  database: 'mydb',
  connectionTimeout: 5000,
  server: 'host\\instance',
  pool: {
    max: 10,
    min: 0,
    idleTimeoutMillis: 3000,
  },
  options: {
    encrypt: false
  },
}
```

**Comment by juanluispaz** [comment]
Hi, 

I'm not sure if I understand your question correctly. It is never the intention of ts-sql-query to hide the appropriate connector you use; when you create a ts-sql-query connection, you must provide a database connection or pool created with your connector. In the case of mssql you probably want to work with a connection pool; for that, you will need to use [MssqlPoolQueryRunner](https://ts-sql-query.readthedocs.io/en/stable/query-runners/recommended-query-runners/#mssql-with-a-connection-pool) or [MssqlPoolPromiseQueryRunner](https://ts-sql-query.readthedocs.io/en/stable/query-runners/recommended-query-runners/#mssql-with-a-connection-pool-promise), this class receives in the constructor an instance of mssql connection pool.

For short, ts-sql-query doesn't manage connection strings; you must provide a valid object of your connector. The fact ts-sql-query doesn't hide the connector allows you to do more complex things; the way that objects are initialised depends on you and the connector (in your case mssql)

Then, in your case, the `sqlConfig` you provided will remain valid. Additionally, you must create the mssql connection pool on your own.

**Example**:

```ts
import { ConnectionPool } from 'mssql'
import { MssqlPoolQueryRunner } from "./queryRunners/MssqlPoolQueryRunner"

const sqlConfig = {
  user: 'User',
  password: 'Password',
  database: 'mydb',
  connectionTimeout: 5000,
  server: 'host\\instance',
  pool: {
    max: 10,
    min: 0,
    idleTimeoutMillis: 3000,
  },
  options: {
    encrypt: false
  },
}

const poolPromise = new ConnectionPool(sqlConfig).connect(); // <---- Mssql connection pool (this is not a ts-sql-query object)

async function main() {
    const mssqlPool = await poolPromise
    const connection = new DBConnection(new MssqlPoolQueryRunner(mssqlPool))
    // Do your queries here
}
```

Let me know if I have answered your question.

**Comment by juanluispaz** [comment]
One additional note: Do not reuse ts-sql-query connections, even if you provide a pool; ts-sql-query represents a dedicated connection; then do not share that object across multiple requests in express (or similar); instead, create and ts-sql-query connection object (providing the pool) in each express' request

**Comment by runar-rkmedia** [comment]
Oh, I'm so sorry, I must have posted this into the wrong project.
