### ISSUE TITLE
What's the recommended way of tracking errors?

### ISSUE THREAD

**Issue by beverloo** [juanluispaz/ts-sql-query#111]
Hi Juan - thank you so much for this amazing library! I've been having a lot of fun integrating it in one of my personal projects 😃 

What is the recommended way of tracking errors that occur during query execution, for example because the database scheme changed without updating the `ts-sql-query` table definitions? My goal is to capture such errors and separately write them to a log, to eventually enable alerting. I'm using pool-based MariaDB connections.

There are a few options that I've considered:
1. Add a Promise rejection handler to each execution, which works but is a bit fragile as it's easy to forget.
2. Override the protected methods in the `MariaDBQueryRunner` that end up calling MariaDB's `Connection.query()` and attach a rejection handler before returning it. This is a bit fragile as new calls may be added silently.
3. Override MariaDB's `Connection.query()` and handle it there outside of `ts-sql-query`. This is probably most stable, but I'm less comfortable with it because it's another level of indirection away from my own code.

I also tried to observe MariaDB's `Connection::on("error")` events. When I attach the listener after the `Pool::on("acquire")` event the `error` event does not get fired. Probably because that event only deals with connection errors?

The second option is the one I'm pursuing ([code](https://github.com/beverloo/volunteer-manager/blob/main/app/lib/database/Connection.ts#L70), which isn't too bad), but wanted to check if there's a better option I'm not aware of?

**Comment by juanluispaz** [comment]
Hi,

I recommend to evaluate the possibility to you create your own query runner that intercepts MariaDB one; you can use [InterceptorQueryRunner](https://ts-sql-query.readthedocs.io/en/stable/query-runners/general-purpose-query-runners/#interceptorqueryrunner) [(class code)](https://github.com/juanluispaz/ts-sql-query/blob/master/src/queryRunners/InterceptorQueryRunner.ts), [LoggingQueryRunner](https://ts-sql-query.readthedocs.io/en/stable/query-runners/general-purpose-query-runners/#loggingqueryrunner) [(class code)](https://github.com/juanluispaz/ts-sql-query/blob/master/src/queryRunners/LoggingQueryRunner.ts) or [ChainedQueryRunner](https://github.com/juanluispaz/ts-sql-query/blob/master/src/queryRunners/ChainedQueryRunner.ts) as your base class.

I do not recommend extending MariaBD query runner; that will make it harder to maintain it, and you will be coupled to the current implementation. If something changes in the future, it may not behave as you expected.

We use the interceptor approach to track what is happening with our queries and to write it in the log.

In this way, your database initialization will look like: 

```ts
const connection = new DBConnection(new MyInterceptorQueryRunner(new MariaDBPoolQueryRunner(pool)))
```

With this, your code can look like:

```ts
class MyInterceptorQueryRunner extends InterceptorQueryRunner<undefined> {
    private logError(error: SqlError): void {
        if (!error.message.includes('database-error')) {
            Log({
                type: LogType.DatabaseError,
                severity: LogSeverity.Error,
                data: {
                    message: error.message,
                    query: error.sql,
                },
            });
        }
    }

    onQuery(queryType: QueryType, query: string, params: any[]): undefined {
        return undefined;
    }
    onQueryResult(queryType: QueryType, query: string, params: any[], result: any, playload: undefined): void {
        return;
    }
    onQueryError(queryType: QueryType, query: string, params: any[], error: any, playload: undefined): void {
        this.logError(error);
    }
}
```

This class will replace `QueryRunner` and `PoolQueryRunner` in your code, and your code will be clean of any details regarding the internal implementation of how the queries are executed in MariaBD.

Let me know if this is useful for you.

**Comment by beverloo** [comment]
Perfect, that's much cleaner! Thank you so much 😃 

https://github.com/beverloo/volunteer-manager/commit/b40c9a05f6c3946686c884369719e0cb9b7f94eb
