### ISSUE TITLE
Feature Request: ReadOnlyQueryRunner

### ISSUE THREAD

**Issue by thekevinbrown** [juanluispaz/ts-sql-query#128]
I have a use case of a dry run. In this scenario it'd be really nice to have a read only query runner which wraps any other query runner. It'd return the results of selects as normal, but for updates, inserts, and deletes it'd just log the query.

Is this something you'd accept a PR for?

**Comment by juanluispaz** [comment]
Hi,

We are facing similar needs, but we need to throw an error instead of logging the query.

The PR is welcome if you have something prepared; if you still need to, I will prepare something reusable.

Let me know.

**Comment by thekevinbrown** [comment]
I haven't built anything yet, wanted to judge interest before I devoted time to it, so would definitely be happy to assist with whatever you're cooking up @juanluispaz!
