### ISSUE TITLE
Sync transactions

### ISSUE THREAD

**Issue by threema-danilo** [juanluispaz/ts-sql-query#16]
I'm using a [synchronous query runner](https://ts-sql-query.readthedocs.io/en/stable/advanced-usage/#synchronous-query-runners) with a `sync`-adapter similar to the one you proposed in the docs.

This works nicely, but there's one issue: Transactions only support async closures inside.

https://github.com/juanluispaz/ts-sql-query/blob/84ddc2c022c8020835596fe39d154b86824ea7ba/src/connections/AbstractConnection.ts#L54-L63

This means that a transaction which runs only synchronous code (using the `sync` adapter) converts this synchronous code in real-asynchronous code, which cannot be converted to sync again with the adapter.

Do you have a good solution in mind for this? I could build my own transaction mechanism, but maybe a solution directly in this project might be an option. Maybe a `syncTransaction` method that should only be used with synchronous runners? Or simply new overloads for non-async closures, that shouldn't be used for async runners? (I think that last approach could work, it's pretty obvious that you cannot use the sync closure if you await inside.)

**Comment by juanluispaz** [comment]
Hi!

Wonderful it is useful to you.

ts-sql-query offers you to manage the transaction at high-level and at low-level. The one you shown the code you is a high level. The high-level one is just a shortcut to the low-level (except in the case of Prisma, where low-level is not possible).

I propose to you create you own transaction function with your sync adapter, you can add to your transaction object. It will lock like this in your code:

```ts
class DBConection extends SqliteConnection<'DBConnection'> { 
    syncTransaction<T>(fn: () => T): T {
        sync(this.beginTransaction())
        let needRollback = true
        try {
            const result = fn()
            needRollback = false
            return result
        } finally {
            if (needRollback) {
                // there is an exception comming from fn
                try {
                    sync(this.rollback())
                } catch {
                    // ignore this one to allow the exception comming from fn be the one thrown
                }
            } else {
                sync(this.commit())
            }
        }
    }
}
```

Then you can use it in your code like:

```ts
connection.syncTransaction(() -> {
     connection.update...
})
```

Whatever is returned by the inner function is going to be the result of the `syncTransaction` function.

Be aware, the proposed solution depends on your own `sync` function implementation. This is the easiest solution and it is going to work as you expected. That is what the `executeInTransaction` method do in the case of sqlite (this method is different if you use `PrismaQueryRunner`, but that is not your case).

The less intuitive solution is any promise returned by ts-sql-query using a synchronous query runner is a synchronous promise; that implies if the `transaction` method receives a function that returns a synchronous promise the result of the method is a synchronous promise that you can apply your own sync function; but the consequence of this is the inner function must return a sync promise (could be a resolved one). 

My suggestion for you is to use the `syncTransaction` function, it is easier to understand and to use in the code.

**Comment by threema-danilo** [comment]
Sure, that works for me! I just wanted to bring it up, in case other people have the same issue as well 🙂

**Comment by juanluispaz** [comment]
Marvellous, thanks!
