### ISSUE TITLE
Is code generating in your road? 

### ISSUE THREAD

**Issue by xialvjun** [juanluispaz/ts-sql-query#2]
There are so many definitions to write. 

If only `ts-sql-query` can query the database and generate the code for use.

**Comment by xialvjun** [comment]
This feature can be integrated into CI system to make sure your sql is right.

**Comment by lorefnon** [comment]
I am trying to introduce this library in an existing project with a few hundred tables and creating table mappings for each table is proving to be arduous.

I have an early stage code-generator here: https://github.com/lorefnon/ts-sql-codegen
This is only tested with postgres so far, but the core is fairly extensible. 
Any feedback/suggestions/contributions are welcome.

**Comment by juanluispaz** [comment]
Oh, that is wonderful, it looks very good.

I will include a reference to it in the documentation when I publish an update.

I was reviewing your code a little bit, I see you are dealing with most of the types, but I was not able to see double data type support; by example, it is not [here](https://github.com/lorefnon/ts-sql-codegen/blob/d094341b4a152a12de1e7fbe2de3e4b1d4095a00/src/field-mappings.ts#L33)

**Comment by juanluispaz** [comment]
Great!!!

It will be really useful if you handle as well views in the database.

Regarding stringInt and stringDouble, usually, the database connectors returns a string when the number returned by the database cannot be represented in a safe way; these types are here to represent the value can be a number or a string. Be aware this behaviour depends on your database connector and the type used in the database. If you use an int8 value (in PostgreSQL) you can use an stringInt or a bigint in JavaScript (pg returns string by default, if you use bigint, ts-sql-query will parse it for you); but, if you use a numeric type (pg will returns it as string) that is big, you will needs to use stringDouble, if you use double you will lost precision.

bigint is new in JavaScript, that reduce the needs of stringInt, but some projects still using the string behaviour; unfortunately, there is no big number standardised yet. 

Typically the parse of the numeric values coming from the database are preformed by the connector (ts-sql-query manage any mismatch, by example a bigint when the value is represented as string); but there is no way to ts-sql-query say to the connector what is the expected type; then any precession lost need to be fixed using the proper connector with the proper configuration. In the case of PostgreSQL, out of the box have no issues.

**Comment by lorefnon** [comment]
@juanluispaz Understood - Thanks for the elaboration. For now I'll leave the default mappings to not use string* types, and assume that users will be willing to customize the mappings if needed. Though I think bigint behavior will need to change - I'll explore some more around this. 

Views are supported now.

**Comment by juanluispaz** [comment]
Reference added to https://github.com/lorefnon/ts-sql-codegen in the documentation and readme.

**Comment by juanluispaz** [comment]
Code generation already covered by [ts-sql-codegen](https://github.com/lorefnon/ts-sql-codegen). I close this issue because the functionality is already available.
