### ISSUE TITLE
Naming of >= and <= operators

### ISSUE THREAD

**Issue by threema-danilo** [juanluispaz/ts-sql-query#21]
Right now the operators for `<` and `>` are called `smaller` and `larger`. It took me a long time and grepping the source code, to realize that `<=` and `>=` are `smallAs` and `largeAs`.

I find this terminology a big confusing. How about renaming those to `smallerOrEqual` and `largerOrEqual`? It's a bit longer, but it should be easier to understand and discover.

**Comment by juanluispaz** [comment]
This naming thing is a complicated topic; I reviewed a lot of different projects that have something similar and it looks like there is no way no to have a shared naming convention.

I like the names that you propose; I'm thinking to add smallerOrEqual as alias to smallAs and largerOrEqual as alias to largeAs. I don't want to rename this functions right now because it will break the compatibility.

What do you think?

**Comment by juanluispaz** [comment]
There are several years from now that I implemented the comparison functions 

I'm reviewing the most commons names for that operators in similar libraries in other programming languages nowadays and I found:

| Common operator symbol  | Name in ts-sql-query | Name in JOOQ.            |
| -------------------------- | --------------------- | ----------------------- |
| `=`, `==`                             | `equals`                      | `eq`, `equal`                 |
| `!=`, `<>`                            |  `notEquals`               | `ne`, `notEqual`            |
| `<`                                       | `smaller`                     | `lt`, `lessThan`              |
| `<=`                                     | `smallAs`                    | `le`, `lessOrEqual`        |

le or lessOrEqual(T);                               // <= (some bind value)
le or lessOrEqual(Field<T>);                        // <= (some column expression)
le or lessOrEqual(Select<? extends Record1<T>>);    // <= (some scalar SELECT statement)
gt or greaterThan(T);                               // >  (some bind value)
gt or greaterThan(Field<T>);                        // >  (some column expression)
gt or greaterThan(Select<? extends Record1<T>>);    // >  (some scalar SELECT statement)
ge or greaterOrEqual(T);                            // >= (some bind value)
ge or greaterOrEqual(Field<T>);                     // >= (some column expression)
ge or greaterOrEqual(Select<? extends Record1<T>>); // >= (some scalar SELECT statement)

**Comment by juanluispaz** [comment]
I'm trying to remember why I have chosen those names for the operators. There are several years from now that I implemented the comparison functions. Mostly I picked from different programming languages API trying to find something easy to read without learning a lot of abbreviations or sounds like you are reading the text like a machine. Sqlite and PostgreSQL was my starting point to moderate the API. Additionally, I tried to match JavaScript API.

I'm reviewing the most commons names for that operators in similar libraries in other programming languages nowadays, and I found:

| Common operator symbol  | Name in ts-sql-query | Name in JOOQ             |
| -------------------------- | --------------------- | ----------------------- |
| `=`, `==`                             | `equals`                      | `eq`, `equal`                 |
| `!=`, `<>`                            | `notEquals`                | `ne`, `notEqual`            |
| `<`                                       | `smaller`                     | `lt`, `lessThan`              |
| `<=`                                     | `smallAs`                    | `le`, `lessOrEqual`        |
| `>`                                       | `larger`                        | `gt`, `greaterThan`       |
| `>=`                                     | `largeAs`                     | `ge`, `greaterOrEqual` |
| `is` (sql)                              | `is`                               | ?                                       |
| `is not` (sql)                       | `isNot`                          | ?                                      |
| `between` (sql)                  | `between`                    | `between...and`            |
| `not between` (sql)           | `notBetween`              | `notBetween...and`       |
| `and`, `&&`                        | `and`                            | `and`                              |
| `or`, `ıı`                              | `or`                               | `or`                                 |
| `!`, `not`(prefix)                | `negate`                       | `not` (suffix)                  |
| `concat` (string)                | `concat`                       | `concat`                         |
| `+`                                      | `add`                             | `add`, `plus`                 |
| `-`                                       | `substract`                   | `sub`, `subtract`, `minus` |
| `*`                                       | `multiply`                     | `mul`, `multiply`, `times`            |
| `/`                                       | `divide`                         | `div`, `divide​`                |
| `%`, `mod`                        | `mod`                           | `mod`, `modulo`, `rem` |
| `in` (sql)                             | `in`                               | `in`                                  |
| `not in` (sql)                      | `notIn`                          | `notIn`                            |
| `^`, `power`                      | `power`                        | `pow`, `power`             |

There are a lot more functions. I just listed some of them focused on caparison and arithmetic.

I'm not sure I want to introduce changes in the naming right now. I would prefer to have more feedback on this, study a little more, and choose which must be the naming.

**Comment by juanluispaz** [comment]
I reviewed all the functions that are traslated to SQL 

**General**
| Common operator symbol         | Name in ts-sql-query       | Same name in            | Name in JOOQ               | New name           |
| ------------------------------ | -------------------------- | ----------------------- | -------------------------- | ------------------ |
| `=`, `==`                      | `equals`                   |                         | `eq`, `equal`              |                    |
| `!=`, `<>`                     | `notEquals`                |                         | `ne`, `notEqual`           |                    |
| `<`                            | `smaller`                  |                         | `lt`, `lessThan`           | `lessThan`         |
| `<=`                           | `smallAs`                  |                         | `le`, `lessOrEqual`        | `lessOrEquals`     |
| `>`                            | `larger`                   |                         | `gt`, `greaterThan`        | `greaterThan`      |
| `>=`                           | `largeAs`                  |                         | `ge`, `greaterOrEqual`     | `greaterOrEquals`  |
| `is` (sql)                     | `is`                       | sqlite                  | ?                          |                    |
| `is not` (sql)                 | `isNot`                    | sqlite                  | ?                          |                    |
| `between` (sql)                | `between`                  | sqlite                  | `between...and`            |                    |
| `not between` (sql)            | `notBetween`               | sqlite                  | `notBetween...and`         |                    |
| `and`, `&&`                    | `and`                      | sqlite                  | `and`                      |                    |
| `or`, `ıı`                     | `or`                       | sqlite                  | `or`                       |                    |
| `!`, `not`(prefix)             | `negate` (suffix)          |                         | `not` (suffix)             |                    |
| `in` (sql)                     | `in`                       | sqlite                  | `in`                       |                    |
| `not in` (sql)                 | `notIn`                    | sqlite                  | `notIn`                    |                    |

**Numeric**
| Common operator symbol         | Name in ts-sql-query       | Same name in            | Name in JOOQ               | New name           |
| ------------------------------ | -------------------------- | ----------------------- | -------------------------- | ------------------ |
| `+`                            | `add`                      |                         | `add`, `plus`              |                    |
| `-`                            | `substract`                |                         | `sub`, `subtract`, `minus` |                    |
| `*`                            | `multiply`                 |                         | `mul`, `multiply`, `times` |                    |
| `/`                            | `divide`                   |                         | `div`, `divide`            |                    |
| `%`, `mod`                     | `mod`                      | sqlite                  | `mod`, `modulo`, `rem`     |                    |
| `^`, `power`, `pow`            | `power`                    | sqlite                  | `pow`, `power`             |                    |
| `abs`                          | `abs`                      | js, sqlite              | `abs`                      |                    |
| `ceil`                         | `ceil`                     | js, sqlite              | `ceil`                     |                    |
| `floor`                        | `floor`                    | js                      | `floor`                    |                    |
| `round`                        | `round`                    | js, sqlite              | `round`                    |                    |
| `round` (_, n)                 | `roundn`                   | sqlite (round overload) | `round` (round overload)   |                    |
| `exp`                          | `exp`                      | js, sqlite              | `exp`                      |                    |
| `ln`                           | `ln`                       | js                      | `ln`                       |                    |
| `log10`                        | `log10`                    | js, sqlite              | ?                          |                    |
| `log` (_, n)                   | `logn`                     | sqlite (log overload)   | `log` (base argument)      |                    |
| `sqrt`                         | `sqrt`                     | js, sqlite              | `sqrt`                     |                    |
| `cbrt`                         | `cbrt`                     | js                      | ?                          |                    |
| `sign`                         | `sign`                     | js, sqlite              | `sign`                     |                    |
| `acos`                         | `acos`                     | js, sqlite              | `acos`                     |                    |
| `asin`                         | `asin`                     | js, sqlite              | `asin`                     |                    |
| `atan`                         | `atan`                     | js, sqlite              | `atan`                     |                    |
| `atan2`                        | `atan2`                    | js, sqlite              | `atan2`                    |                    |
| `cos`                          | `cos`                      | js, sqlite              | `cos`                      |                    |
| `cot`                          | `cot`                      | (2)                     | `cot`                      |                    |
| `sin`                          | `sin`                      | js, sqlite              | `sin`                      |                    |
| `tan`                          | `tan`                      | js, sqlite              | `tan`                      |                    |
| `minValue`                     | `minValue`                 | js, sqlite (1)          | ?                          |                    |
| `maxValue`                     | `maxValue`                 | js, sqlite (1)          | ?                          |                    |

**String**
| Common operator symbol         | Name in ts-sql-query       | Same name in            | Name in JOOQ               | New name           |
| ------------------------------ | -------------------------- | ----------------------- | -------------------------- | ------------------ |
| `concat` (string)              | `concat`                   | js                      | `concat`                   |                    |
| `equals` (Insensitive)         | `equalsInsensitive`        |                         | `equalIgnoreCase`          |                    |
| `not equals` (Insensitive)     | `notEqualsInsensitive`     |                         | `notEqualIgnoreCase`       |                    |
| `like`                         | `like`                     | sqlite                  | `like`                     |                    |
| `not like`                     | `notLike`                  | sqlite                  | `notLike`                  |                    |
| `like` (Insensitive)           | `likeInsensitive`          | (3)                     | `likeIgnoreCase`           |                    |
| `not like`(Insensitive)        | `notLikeInsensitive`       | (3)                     | `notLikeIgnoreCase`        |                    |
| `startsWith`                   | `startsWith`               | (3) js                  | `startWith`                |                    |
| `not startsWith`               | `notStartsWith`            | (3) js                  | ?                          |                    |
| `endsWith`                     | `endsWith`                 | (3) js                  | `endsWith`                 |                    |
| `not endsWith`                 | `notEndsWith`              | (3) js                  | ?                          |                    |
| `startsWith` (Insensitive)     | `startsWithInsensitive`    | (3) js                  | `startWithIgnoreCase`      |                    |
| `not startsWith` (Insensitive) | `notStartsWithInsensitive` | (3) js                  | ?                          |                    |
| `endsWith` (Insensitive)       | `endsWithInsensitive`      | (3) js                  | `endsWithIgnoreCase`       |                    |
| `not endsWith` (Insensitive)   | `notEndsWithInsensitive`   | (3) js                  | ?                          |                    |
| `contains`                     | `contains`                 | (3)                     | `contains`                 |                    |
| `not contains`                 | `notContains`              | (3)                     | `noContains`               |                    |
| `contains` (Insensitive)       | `containsInsensitive`      | (3)                     | `containsIgnoreCase`       |                    |
| `not contains` (Insensitive)   | `notContainsInsensitive`   | (3)                     | `notContainsIgnoreCase`    |                    |
| `lower`                        | `lower`                    | (4) sqlite              | `lower`                    | ? (4)              |
| `upper`                        | `upper`                    | (4) sqlite              | `upper`                    | ? (4)              |
| `length`                       | `length`                   | js, sqlite              | `length`                   |                    |
| `trim`                         | `trim`                     | js, sqlite              | `trim`                     |                    |
| `ltrim`                        | `ltrim`                    | (5) sqlite              | `ltrim`                    | ? (5)              |
| `rtrim`                        | `rtrim`                    | (5) sqlite              | `rtrim`                    | ? (5)              |
| `reverse`                      | `reverse`                  | sqlite                  | `reverse`                  |                    |
| `substring`                    | `substring`                | js, sqlite              | `substring`                |                    |
| `substringToEnd`               | `substringToEnd`           | js, sqlite (6)          | `substring` (overload)     |                    |
| `replace`                      | `replace`                  | js, sqlite              | `replace`                  |                    |

**String**
| Common operator symbol         | Name in ts-sql-query       | Same name in            | Name in JOOQ               | New name           |
| ------------------------------ | -------------------------- | ----------------------- | -------------------------- | ------------------ |
| `getFullYear`                  | `getFullYear`              | js                      | `year`                     |                    |
| `getMonth`                     | `getMonth`                 | js                      | `month` (7)                |                    |
| `getDate`                      | `getDate`                  | js                      | `day`                      |                    |
| `getDay`                       | `getDay`                   | js                      | ?                          |                    |
| `getHours`                     | `getHours`                 | js                      | `hour`                     |                    |
| `getMinutes`                   | `getMinutes`               | js                      | `minute`                   |                    |
| `getSeconds`                   | `getSeconds`               | js                      | `second`                   |                    |
| `getMilliseconds`              | `getMilliseconds`          | js                      | ?                          |                    |
| `getTime`                      | `getTime`                  | js                      | `epoch`                    |                    |

**General functions** (available in the connection object)
| Common operator symbol         | Name in ts-sql-query       | Same name in            | Name in JOOQ               | New name           |
| ------------------------------ | -------------------------- | ----------------------- | -------------------------- | ------------------ |
| `default`                      | `default`                  | sqlite                  | `defaultValue`             |                    |
| `pi`                           | `pi`                       | sqlite                  | `pi`                       |                    |
| `random`                       | `random`                   | sqlite                  | `rand`                     |                    |
| `currentDate`                  | `currentDate`              | sql                     | `currentDate`              |                    |
| `currentTime`                  | `currentTime`              | sql                     | `currentLocalTime`         |                    |
| `currentDateTime`              | `currentDateTime`          | sql                     | `currentInstant`           |                    |
| `currentTimestamp`             | `currentTimestamp`         | sql                     | `currentInstant`           |                    |
| `true`                         | `true`                     | sqlite                  | ?                          |                    |
| `false`                        | `false`                    | sqlite                  | ?                          |                    |
| `exists`                       | `exists`                   | sqlite                  | `exists`                   |                    |
| `not exists`                   | `notExists`                | sqlite                  | `notExists`                |                    |

**Aggregate functions** (available in the connection object)
| Common operator symbol         | Name in ts-sql-query       | Same name in            | Name in JOOQ               | New name           |
| ------------------------------ | -------------------------- | ----------------------- | -------------------------- | ------------------ |
| `count(*)`                     | `countAll`                 | sqlite (readed)         | `count` (overload)         |                    |
| `count(value)`                 | `count`                    | sqlite                  | `count`                    |                    |
| `count(distinct value)`        | `countDistinct`            | sqlite                  | `countDistinct`            |                    |
| `max(value)`                   | `max`                      | sqlite                  | `max`                      |                    |
| `min(value)`                   | `min`                      | sqlite                  | `min`                      |                    |
| `sum(value)`                   | `sum`                      | sqlite                  | `sum`                      |                    |
| `sum(distinct value)`          | `sumDistinct`              | sqlite                  | `sumDistinc`               |                    |
| `avg(value)`                   | `average`                  | sqlite                  | `avg`                      |                    |
| `avg(disctinct value)`         | `averageDistinct`          | sqlite                  | `avg`                      |                    |
| `group_concat(value, sep)`     | `stringConcat`             | some sql                | `groupConcat`              |                    |
| `group_concat(distinct v, s)`  | `stringConcatDistinct`     | some sql                | `groupConcatDistinc`       |                    |


Notes:
1. Word `Value` added to avoid colission with the aggregate operator
2. To review `cot` function, not supported by sqlite, but it is in the public interface
3. `like` variants
4. In JavaScript is `toLowerCase` & `toUpperCase`
5. In JavaScript is `trimLeft` & `trimRight`
6. Added `ToEnd` to avoid overload
7. Date and time functions are modelated after JS Date object, and the result of the functions are the same
8. There is no function to change the sign of a number, and, I'm not sure which one must be the name of this function

**Summary**

Functions with a clear new name

| Name in ts-sql-query       | New name           |
| -------------------------- | ------------------ |
| `smaller`                  | `lessThan`         |
| `smallAs`                  | `lessOrEquals`     |
| `larger`                   | `greaterThan`      |
| `largeAs`                  | `greaterOrEquals`  |

Functions that maybe can have a new name to align with JavaScript

| Name in ts-sql-query       | New name           |
| -------------------------- | ------------------ |
| `lower`                    | `toLowerCase`      |
| `upper`                    | `toUpperCase`      |
| `ltrim`                    | `trimLeft`         |
| `rtrim`                    | `trimRight`        |

Regarding the first group, I'm thinking to create a copy of the methods with the new names and depercate the previous one.
Regarding the secons groupt, I'm not sure.

I will appreciate your feedback

**Comment by alacambra** [comment]
I would go for the jooq notation. It is clear and also known. Whatever name is taken, I would clearly use the "equal" suffix instead of "as".

**Comment by juanluispaz** [comment]
Implemented changes that align method names with convention, where ts-sql-query tries to use well known method names, giving preferences to already existing names in JavaScript, o well known function names in SQL, avoiding abbreviations. Methods with new names:

| Previous name       | New name           |
| -------------------------- | ------------------ |
| `smaller`                  | `lessThan`         |
| `smallAs`                  | `lessOrEquals`     |
| `larger`                   | `greaterThan`      |
| `largeAs`                  | `greaterOrEquals`  |
| `mod`                      | `modulo`           |
| `lower`                    | `toLowerCase`      |
| `upper`                    | `toUpperCase`      |
| `ltrim`                    | `trimLeft`         |
| `rtrim`                    | `trimRight`        |

Previous names are still available as deprecated methods.

This change is not published yet in npm.

**Comment by juanluispaz** [comment]
Changes included in ts-sql-query 1.15.0 now published

**Comment by juanluispaz** [comment]
Changes included in ts-sql-query 1.16.0 now published (skip the previous version due a small bug)

**Comment by threema-danilo** [comment]
Great, thank you, and sorry for not replying earlier (I was away in vacations).

These changes look like a clear improvement to me! I agree with the "alias and deprecate" approach.
