### ISSUE TITLE
Define foreign keys

### ISSUE THREAD

**Issue by Dominik-Reinert** [juanluispaz/ts-sql-query#3]
Hello there,

I see that we can define left(outer)joins already, but I am not sure how I can define a foreign key? 

Is that possible already?

**Comment by juanluispaz** [comment]
Hi,

You don't need to define a column as a foreign key, you only define the shape of the tables, any constrain, or validation in the database is not important during the mapping of the structure of the table.

Quick answer, you don't need it at this level; define a foreign key is important in the database, but not impose extra constraints when you write a query.
