### ISSUE TITLE
Support for upsert

### ISSUE THREAD

**Issue by threema-danilo** [juanluispaz/ts-sql-query#32]
Is there already a way to execute upsert queries (update if a value exists, insert it otherwise)?

In SQLite and PostgreSQL, this is done with `ON CONFLICT DO UPDATE`:

- https://www.sqlite.org/lang_UPSERT.html
- https://www.postgresql.org/docs/9.5/sql-insert.html

MySQL does it a bit differently: https://www.techbeamers.com/mysql-upsert/

I'm not sure how feasible this is, I guess for now we'll have to use transactions.

**Comment by juanluispaz** [comment]
It is not supported yet, I want to find a way to implement it, maybe a subset at the beginning; this clause is a mess across different databases.

Please, can you include some examples of the kind of queries you want to build and I will try to support it.

The workaround right now [customizing the generated sql](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/#customizing-an-insert) with an `afterQuery` sql fragment.

**Comment by juanluispaz** [comment]
Release ts-sql-query 1.26.0 with support to "insert on conflict do nothing" and "insert on conflict do update" on PostgreSql, Sqlite, MariaDB and MySql.

See documentation [here](https://ts-sql-query.readthedocs.io/en/stable/queries/insert/#insert-on-confict-do-nothing)

**Comment by threema-danilo** [comment]
The current use case is "create an entry if the key is missing, update the entry if it exists":

```typescript
this._db.syncTransaction(() => {
    const isKeyPresent: boolean =
        sync(
            this._db
                .selectFrom(tSettings)
                .where(tSettings.key.is(key))
                .selectOneColumn(tSettings.value)
                .executeSelectMany(),
        ).length > 0;

    if (isKeyPresent) {
        sync(
            this._db
                .update(tSettings)
                .set({value})
                .where(tSettings.key.equals(key))
                .executeUpdate(),
        );
    } else {
        sync(this._db.insertInto(tSettings).set({key, value}).executeInsert());
    }
}, this._log);
```

...which works fine but looks a bit awkward.

I tried your suggestion like this:

```typescript
sync(
    this._db
        .insertInto(tSettings)
        .set({key, value})
        .customizeQuery({
            afterQuery: this._db.rawFragment`ON CONFLICT(key) DO UPDATE SET value='asdf'`,
        })
        .executeInsert(),
);
```

This results in this SQL being executed:

```sql
insert into settings ("key", value) values ('mySetting', 'the setting value')
ON CONFLICT(key) DO UPDATE SET value='asdf'
```

The problems with this approach:

- I have to hardcode the key name
- I have to put the value into the fragment string and would need to manually escape it, using `?` doesn't work
- Because the value must be embedded, the type conversion rules from the connection aren't applied

For now, this isn't really a viable solution (when parametrized) and the select-then-insert-or-update transaction works better.

**Comment by juanluispaz** [comment]
Try the latest version, now you can do:

```ts
sync(
    this._db
        .insertInto(tSettings)
        .set({key, value})
        .onConflictOn(tSettings.key)
        .doUpdateSet({value})
        .executeInsert(),
);
```

Note: Maybe you want to use an omit function to exclude the key from the object that contains the values, as a way to repeat yourself.

```ts
const sets = {key, value}
sync(
    this._db
        .insertInto(tSettings)
        .set(sets)
        .onConflictOn(tSettings.key)
        .doUpdateSet(omit(sets, 'key')
        .executeInsert(),
);
```

Additionally, you can omit which key create the conflict if you want that construction.

```ts
sync(
    this._db
        .insertInto(tSettings)
        .set({key, value})
        .onConflictDoUpdateSet({value})
        .executeInsert(),
);
```

Please, try it and share some feedback.

**Comment by threema-danilo** [comment]
Ohh, I totally overlooked your last comment.

> Release ts-sql-query 1.26.0 with support to "insert on conflict do nothing" and "insert on conflict do update" on PostgreSql, Sqlite, MariaDB and MySql.

Crazy, thanks a lot 🙂 I'll test it and will give you feedback.

**Comment by juanluispaz** [comment]
One additional thing, on raw fragments you can do:

```ts
sync(
    this._db
        .insertInto(tSettings)
        .set({key, value})
        .customizeQuery({
            afterQuery: this._db.rawFragment`ON CONFLICT(key) DO UPDATE SET value=${value}`,
        })
        .executeInsert(),
);
```

**Comment by threema-danilo** [comment]
I used `onConflictOn` / `doUpdateSet` and it works perfectly. Thanks for the quick feature release! In case we run into any issues, I'll let you know.
