### ISSUE TITLE
Support for window functions and CTE

### ISSUE THREAD

**Issue by gitkeerthi** [juanluispaz/ts-sql-query#33]
Hi,
Are there any support for window functions and CTE? 

References:
https://www.postgresqltutorial.com/postgresql-window-function/
https://www.postgresqltutorial.com/postgresql-cte/

Thanks.

**Comment by juanluispaz** [comment]
Hi,

The with clause used in CTE is already supported, see [the documentation](https://ts-sql-query.readthedocs.io/en/stable/queries/select/#using-a-select-as-a-view-in-another-select-query-sql-with-clause) and [the issue #31](https://github.com/juanluispaz/ts-sql-query/issues/31) to see more details.

Regarding the window functions, it is not included in the library yet, this feature is quite complex and each database manage in a different way. But, this must not be a limitation for you, you can use [SQL Fragments](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/) to put the window function in your select, if you need to use the window clause of the select (to create named windows) you can use the [custom window](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/#customizing-a-select) in the query customisation.

**Comment by juanluispaz** [comment]
Please, notice aggregate function are already supported as methods of the connection object:

```ts
    countAll(): NumberValueSource
    /** count(value) */
    count(value: ValueSource): NumberValueSource
    /** count(distinct value) */
    countDistinct(value: ValueSource): NumberValueSource
    /** max(value) */
    max<TYPE extends ComparableValueSource>(value: TYPE): TYPE
    /** min(value) */
    min<TYPE extends ComparableValueSource>(value: TYPE): TYPE
    /** sum(value) */
    sum(value: NumberValueSource): NumberValueSource
    sum(value: StringNumberValueSource): StringNumberValueSource
    /** sum(distinct value) */
    sumDistinct(value: NumberValueSource): NumberValueSource
    sumDistinct(value: StringNumberValueSource): StringNumberValueSource
    /** avg(value) */
    average(value: NumberValueSource): NumberValueSource
    average(value: StringNumberValueSource): StringNumberValueSource
    /** avg(disctinct value) */
    averageDistinct(value: NumberValueSource): NumberValueSource
    averageDistinct(value: StringNumberValueSource): StringNumberValueSource
    /** group_concat(value, separator) sometimes called string_agg or listagg. The default separator is ',' */
    stringConcat(value: StringValueSource, separator?: string): StringValueSource
    /** group_concat(distinct value, separator) sometimes called string_agg or listagg. The default separator is ',' */
    stringConcatDistinct(value: StringValueSource, separator?: string): StringValueSource
```

See [connection documentation](https://ts-sql-query.readthedocs.io/en/stable/supported-operations/#connection-definition) for more information
