### ISSUE TITLE
Using a select as a view in another select query without WITH

### ISSUE THREAD

**Issue by mkupriichuk** [juanluispaz/ts-sql-query#36]
Hello
I need to define "subselect' and use it in main select query. Im try some like this:

```javascript
const offersCountLeftJoinedTable = this.connection
    .selectFrom(this.brandTable)
    .leftJoin(productLeftJoinedTable)
    .on(productLeftJoinedTable.brandId.equals(this.brandTable.id))
    .leftJoin(mpOfferLeftJoinedTable)
    .on(productLeftJoinedTable.id.equals(mpOfferLeftJoinedTable.productId))
    .leftJoin(categoryRelationLeftJoinedTable)
    .on(categoryRelationLeftJoinedTable.childCategoryId.equals(productLeftJoinedTable.categoryId))
    .where(mpOfferLeftJoinedTable.isDeleted.equals(filters.offerDeleted || false))
    .and(categoryRelationLeftJoinedTable.parentCategoryId.inIfValue(categoryId))
    .select({
      count: this.connection.count(mpOfferLeftJoinedTable.id),
      brandId: this.brandTable.id
    })
    .groupBy(this.brandTable.id)
    .forUseInQueryAs('_offersCount')
    .forUseInLeftJoin();
```
Then:

```javascript
    const query = this.connection
      .selectFrom(this.brandTable)
      .leftJoin(offersCountLeftJoinedTable) // table from 'subquery'
      .on(offersCountLeftJoinedTable.brandId.equals(this.brandTable.id))
      .where(offersCountLeftJoinedTable.count.greaterThan(0))
      .or(this.brandTable.id.inIfValue(filters.brandId))
      .select({
        id: this.brandTable.id,
        name: this.brandTable.name,
        offersCount: offersCountLeftJoinedTable.count
      })
      .groupBy(this.brandTable.id)
      .orderBy('name', 'asc');
```
 
As result i get the next query
```sql
WITH _offersCount AS
(SELECT
    count(mp_offer.id) AS COUNT,
    brand.id AS brandId
FROM brand
   LEFT JOIN product ON product.brandId = brand.id
   LEFT JOIN mp_offer ON product.id = mp_offer.productId
   LEFT JOIN category_relation ON category_relation.childCategoryId = product.categoryId
WHERE
 (mp_offer.isDeleted = 1) = ?
AND
 category_relation.parentCategoryId IN (?)
GROUP BY
 brand.id)
SELECT
 brand.id AS id,
 brand.`name` AS `name`,
 _offersCount.count AS offersCount
FROM
 brand
LEFT JOIN offersCount ON offersCount.brandId = brand.id
WHERE offersCount.count > ?
GROUP BY brand.id
ORDER BY `name` ASC
```

Is there anything I can do to get the final query without ```WITH```. I need to get this

```sql
SELECT
  brand.id AS "id",
  brand.name AS "name",
  _offersCount.count as "offersCount"
FROM
  brand
  LEFT JOIN (
    SELECT
      COUNT(mp_offer.id) as "count",
      brand.id as "brandId"
    FROM
      brand
      LEFT JOIN product ON (product.brandId = brand.id)
      LEFT JOIN mp_offer ON (product.id = mp_offer.productId)
      LEFT JOIN category_relation ON (
        category_relation.childCategoryId = product.categoryId
      )
    WHERE
      mp_offer.isDeleted = 0
      AND category_relation.parentCategoryId IN (11596745011)
    GROUP BY
      brand.id
  ) AS _offersCount ON (_offersCount.brandId = brand.id)
WHERE
  (_offersCount.count > 0)
  OR (brand.id IN (517))
GROUP BY
  brand.id
ORDER BY
  name ASC
```

Thanks

**Comment by juanluispaz** [comment]
Hi,

I'm not sure what are you trying to do; can you explain me what are you trying to archive with this, and why it is not possible to use the with clause, in theory the with clause do in a better way what the inline query in from do; been the with clause the preferred way in sql (the other one is considered legacy).

Note: the `query` query docent contains the where clause `OR (brand.id IN (517))` that you put in the last query (the desired one)

There is something that confuse me, it is the `brand` table usage in the inline query, it looks like you want to use the brand value from the outer query, but that is forbidden (unless you use lateral joins in PostgreSQL, that is expensive); but, you are adding again the `brand` table in the from of the inner query; that will make it safe to use in the with clause.

Can you explain yourself a little bit what are you trying to do?

I find something strange in the generated query (depending on the database you use): `(mp_offer.isDeleted = 1) = ?`

Can you share with me the definition in typescript of the `mp_offer` table and the one for the connection object? please.

**Comment by mkupriichuk** [comment]
Unfortunately at the moment we are using  ```v5 mysql```, which does not support ```WITH```

> Note: the query query docent contains the where clause OR (brand.id IN (517)) that you put in the last query (the desired one)

Yea, ```filters.brandId``` is a optional parameter ```(undefined | number[])```



mp_offer table:
```typescript
class MPOfferTable extends Table<Connection, 'MPOfferTable'> {
  id = this.autogeneratedPrimaryKey('id', 'int');
  mpVendorId = this.column('mpVendorId', 'int');
  internalItemId = this.column('internalItemId', 'string');
  name = this.column('name', 'string');
  cost = this.column('cost', 'double');
  productId = this.optionalColumnWithDefaultValue('productId', 'int');
  sku = this.optionalColumnWithDefaultValue('sku', 'string');
  stockCount = this.optionalColumnWithDefaultValue('stockCount', 'int');
  isDeleted = this.columnWithDefaultValue('isDeleted', 'boolean', new CustomBooleanTypeAdapter(1, 0));
  minOrder = this.columnWithDefaultValue('minOrder', 'int');

  constructor() {
    super('mp_offer');
  }
}
```

**Comment by juanluispaz** [comment]
Released ts-sql-query 1.28.0 that adds compatibility mode to MySql to avoid use the with clause not supported by MySql 5

Fro more details see the [documentation](https://ts-sql-query.readthedocs.io/en/stable/supported-databases/#compatibility-mode)

Please, test it and give me feedback if that resolve your requirement.

Note: I believe in the columns `isDeleted` you do not need `CustomBooleanTypeAdapter` because MySql transform booleans automatically to 0 or 1 (it depends on the version of MySQL)

**Comment by mkupriichuk** [comment]
Hello, thanks for update

Yes, we have added ```protected compatibilityMode = true```. Now we get the final query as we want.

But sometimes get the next error:
```
Forbidden concurrent usage of the query runner was detected when it tried to get a database connection from the pool
```

Actually the query described above is used for get ```Brands```, but we also use ```ts-sql-query``` for get ```Category```, and they dependent on each other.  If we change ```Brands``` or ```Category```, two requests will be sent again.

If we temporarily remove ```Category``` - the request will be sent only for ```Brands```, and there will be no error like above.

**Comment by juanluispaz** [comment]
You will get `Forbidden concurrent usage` error when a race condition is detected trying to get connection from the pool. It is not related to the query itself. This could happen when you create a single connection object globally that serve all HTTP request. Sql connection are stateful and cannot shared across concurrent HTTP request, in consequence ts-sql-query connection object have the same limitation. The solution is create a ts-sql-query connection per http query.

In the [documentation](https://ts-sql-query.readthedocs.io/en/stable/connection-tables-views/#instantiating-the-connection-with-the-database-connection) I tried to explain better:

```
Important: A ts-sql-query connection object and the queries runners objects received as
constructor's arguments represent a dedicated connection; consequently, don't share 
connections between requests when you are handling HTTP requests; create one 
connection object per request with its own query runners. Even when the ts-sql-query 
connection object uses a query runner that receives a connection pool, the ts-sql-query 
connection sill represents a dedicated connection to the database extracted automatically
from the pool and must not be shared.
```

**Comment by mkupriichuk** [comment]
Thanks for the quick replies, all works fine now
