### ISSUE TITLE
Cloudflare frequently blocking documentation site

### ISSUE THREAD

**Issue by lorefnon** [juanluispaz/ts-sql-query#44]
This is probably low priority because the docs are also committed in the repo, but just FYI we (in India) find ourselves frequently blocked when searching the documentation site. 

![image](https://user-images.githubusercontent.com/1449492/178151910-83dfabb1-1c63-45bf-94da-1fc7a77730d7.png)

Cloudflare Ray ID: 728a61ebcb4cc940

Please feel free to close this if this is not actionable at your end.

**Comment by juanluispaz** [comment]
This Cloudflare rule is in your network, and they are enabling very heavy rules; it is not allowing SQL code (the one in the examples).

You can see the same documentation available in the web at https://github.com/juanluispaz/ts-sql-query/tree/master/docs  Try, maybe the rule is more relaxed in GitHub domain.

In the worst case you can download the code, and run locally following the instructions at https://github.com/juanluispaz/ts-sql-query/blob/master/docs/README.md

Try it and let me know.

**Comment by juanluispaz** [comment]
Nothing that I can do on my side. I will close it.
