### ISSUE TITLE
MariaDB supports returning

### ISSUE THREAD

**Issue by oOLooCoreZOo** [juanluispaz/ts-sql-query#51]
Hi,

I am using MariaDB (10.6.10-MariaDB)
Currently ts-sql-query seems not to support returning with from in MariaDB.
Following code will not compile:
          
```
connection.insertInto(aTable)
                .from(
                    connection.selectFrom(otherTable)
                        .where(otherTable.otherId.equals(1))
                        .select({
                            id: otherTable.id,
                        })
                )
                .returningLastInsertedId()   // <--- does not exist
                .executeInsert().then((rowId: any) => {
                       console.log(rowId[0]);
                })
```
Therefore I did following code changes:
src/sqlBuilders/AbstractMySqlMariaBD[sig!]SqlBuilder.ts
```
_buildInsertReturning(query, params) {
        const idColumn = query.__idColumn;
        if (idColumn) {
            this._setContainsInsertReturningClause(params, true);
            return ' returning ' + this._appendSql(idColumn, params); // Empty name for the out params, no special name is requiered
        }

        this._setContainsInsertReturningClause(params, false);
        return '';
    }
```
src/expressions/insert.ts
```
type ReturningLastInsertedIdFromSelectType<TABLE extends ITableOrView<any>> =
    TABLE[typeof database] extends (NoopDB | PostgreSql | SqlServer | Sqlite | MariaDB)
    ? AutogeneratedPrimaryKeyColumnsTypesOf<TABLE> extends never ? never : () =>  CustomizableExecutableInsertReturningLastInsertedId<TABLE, AutogeneratedPrimaryKeyColumnsTypesOf<TABLE>[]>
    : never
```

It seems to work with that.
Other returning functions should be probably also supported.
Tested MariaDB only.
Can you consider to add this to master please?

Best regards,
Chris

**Comment by juanluispaz** [comment]
Oh, wonderful, at the time I wrote that part of the code MariaDB didn't support the returning clause, but starting by MariaBD 10.5 they support returning on insert or delete; but not on update (unfortunately).

The most interesting part is a returning of an insert from select was announced as not supported, even the [documentation](https://mariadb.com/kb/en/insert-select/) doesn't reflect it, but it works.

I'm going to update MariaDB implementation to allow returning on insert, insert from select and delete; additionally, I will put a flag to prefer use returning clause over the autogenerated value returned by the connector; that will remove the restriction __"only autogenerated id can be returned"__

**Comment by juanluispaz** [comment]
Release ts-sql-query 1.39.0 with support to the returning clause when insert or delete in MariaDB; please, review [Last inserted id strategies in MariaDB](https://ts-sql-query.readthedocs.io/en/latest/supported-databases/#last-inserted-id-strategies-in-mariadb)

Please, test it and give me feedback if that resolve your requirement.

**Comment by oOLooCoreZOo** [comment]
Thank you for your fast support.
I can confirm that it is working.

Best regards,
Chris
