### ISSUE TITLE
Sqlite date format is invalid

### ISSUE THREAD

**Issue by wael-jaber** [juanluispaz/ts-sql-query#55]
I don't know if other DBs are affected (didn't have enough time to look into it) . I see the root cause basically the getMonth() methode in node returns the months starting from 0 -> 11 and so dates with december in them will result in YYYY/00/DD and that will throw and error because 0 isn't a valid month.  sorry if I am hard to understand I am not good at explaining and this is my first issue ever on an open source lib.

**Comment by juanluispaz** [comment]
Hi, please can you include an example to me figure out what are you trying to do?

I implemented the date and time Value source according to JS, that means the method getMonth() will return a value between 0-11; some databases represent it using a number between 1-12; I'm reviewing the SQLite implementation (that one is very special) and it is returning a number between 1-12, it is a bug that I will fix.

I'm not sure if that is related with what are your try to describe here, please, let me know more in detail

**Comment by wael-jaber** [comment]
Hello , I think that is the issue I am talking about I will try to provide an example repo for easy reproduction of the bug ( I use better-sqlite3 ) but since I am working of multiple projects at the moment , time is hard to allocate . but if you wanna do it yourself and not waiting on me since I saw about 1,3 k weekly downloads this problem could be affecting a good amount of users . steps to reproduce:

1. set up a db connection with better BetterSqlite3QueryRunner .
2. create a table that has a col with date data type.
3. insert a date (january) then execute a simple insert query . inserting shouldn't throw anything (which in imo should do since YYYY-00-DD is invalid date format in most of the DBs)
4. execute a select query for that for that col , and you will get invalid date coming from db error.

I would suggest to use moment.js or day.js instead of relying on JS native Date class , however a simple fix for this could be is add 1  to each getMonth() call in the transformValueToDB in the AbstractSqliteConnection class.

**Comment by juanluispaz** [comment]
Fixed in ts-sql-query 1.41.0 already published
