### ISSUE TITLE
orderBy field which is not selected

### ISSUE THREAD

**Issue by mkupriichuk** [juanluispaz/ts-sql-query#60]
Hello

Can we ```orderBy``` field which not selected?

Example:
```
class SimilarCategoryTable extends Table<Connection, 'SimilarCategoryTable'> {
  categoryId = this.primaryKey('categoryId', 'string');
  highestRank = this.column('highestRank', 'int');

  constructor() {
    super('sa_similar_category');
  }
}
```

Query:
```
connection
      .selectFrom(similarCategoryTable)
      .select({
        id: similarCategoryTable.categoryId,
        highestRank: similarCategoryTable.highestRank
      })
      .orderBy('highestRank', 'desc')
      .executeSelectMany();
```

Its works but we don`t need ```highestRank``` in result, but still need to ```orderBy``` this field, like:
```
connection
      .selectFrom(similarCategoryTable)
      .select({
        id: similarCategoryTable.categoryId
      })
      .orderBy('highestRank', 'desc')
      .executeSelectMany();
```

I try to use ```orderByFromString(highestRank DESC)``` but its not work.

Is it possible? Thanks

**Comment by juanluispaz** [comment]
Hi,

In current implementation all order by columns must be in the return columns, I've been looking a way to get rid of this. But, I offer you a lot of ways to deal with things not managed by the library. In this case you can look the [query customisation of a select](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/#customizing-a-select), using this feature you can implement it in this way:

```ts
connection
  .selectFrom(similarCategoryTable)
  .select({
    id: similarCategoryTable.categoryId
  })
  .customizeQuery({
    beforeOrderByItems: connection.rawFragment`${similarCategoryTable.highestRank} desc`
  })
  .executeSelectMany();
```

**Comment by mkupriichuk** [comment]
> ```ts
> .customizeQuery({
>     beforeOrderByItems: connection.rawFragment`${similarCategoryTable.highestRank} desc`
>   })
> ```

yes, its works, thanks
