### ISSUE TITLE
Support for porsager/postgres

### ISSUE THREAD

**Issue by lithdew** [juanluispaz/ts-sql-query#61]
Hi,

I wanted to request if it would be possible to have a native query runner for the Node/Deno PostgreSQL client https://github.com/porsager/postgres.

I'd be happy to contribute query runner support for the client, though would like to know if there may be any gotchas I bear in mind before writing the query runner for this client (i.e. porsager/postgres is natively pooled, has support for transactions, etc.).

**Comment by juanluispaz** [comment]
I was just reading about what I need to know to implement this.

An initial approach will be duplicate and adapt the current Pg implementation:
- https://github.com/juanluispaz/ts-sql-query/blob/1.42.0/src/queryRunners/PgPoolQueryRunner.ts
- https://github.com/juanluispaz/ts-sql-query/blob/1.42.0/src/queryRunners/PgQueryRunner.ts

Then a dedicated runnable example (used to validate it works):
- https://github.com/juanluispaz/ts-sql-query/blob/1.42.0/src/examples/PgExample.ts
- https://github.com/juanluispaz/ts-sql-query/blob/1.42.0/scripts/run-all-examples.sh add the new entry here

Add the documentation here: https://github.com/juanluispaz/ts-sql-query/blob/1.42.0/docs/query-runners/recommended-query-runners.md

`npm run all-examples` must run without any error (this takes very long time to execute and requires a lot of space in the disk (see https://github.com/juanluispaz/ts-sql-query/tree/1.42.0/test )

Things that worry me:
- Transaction management, it is different that Pg, similar to the Prisma (already implemented): https://github.com/porsager/postgres#begin--commit-await-sqlbeginoptions---fn---fn
- This query runner will not support low-level transaction management

Due you have shown interest, I'm going to implement it, but, I will need you to provide feedback to me when it is implemented. I will try to implement it tomorrow. Then, I will publish a release to allow you to use it when it is done. I really will appreciate your feedback here. I believe this will be even more recommendable than Pg.

**Comment by juanluispaz** [comment]
Implemented in ts-sql-query 1.43.0 already published, see more details [here](https://ts-sql-query.readthedocs.io/en/stable/query-runners/recommended-query-runners/#postgres).

Please, let me know any feedback.
