### ISSUE TITLE
Convert number to 'table value number'

### ISSUE THREAD

**Issue by mkupriichuk** [juanluispaz/ts-sql-query#68]
Hello
I need divide a default number with value from table:

```
10 / table.age
```

Its any solution for do this without use ```connection.fragmentWithType```.  Maybe some function\method for convert 10 to ```NumberValueSource```?

```
connection.toNumberValueSource(10).divide(table.age)
```

Thanks

**Comment by juanluispaz** [comment]
Hi,

Yes, that already exists, and you are really close. You can do this:

```ts
connection.const(10, 'int')
```

Then you will get a database object that contains the value and you can use in your query in the same way any column.

There is, as well, a variation called `optionalConst` that allows the value to be null
