### ISSUE TITLE
ChainedError: No result returned by the database

### ISSUE THREAD

**Issue by yeongjet** [juanluispaz/ts-sql-query#70]
After calling `executeSelectOne`, If empty result returned from db, this error will be throw. It's not graceful and inconvenient to judge whether data was found(have to catch it). Just return empty result as same as db would be fine.

My codes:
```ts
this.database.selectFrom(tWine).where(tWine.lwin7.equals(1004820)).select(extractColumnsFrom(tWine)).executeSelectOne()
```

Error logs:
```
selectOneRow select wine_id as wineId, lwin7 as lwin7, `name` as `name`, display_name as displayName, winery as winery, `type` as `type`, country as country, region as region, sub_region as subRegion, site as site, photos as photos, create_way as createWay from wine where lwin7 = ? [ 1004820 ]
ChainedError: No result returned by the database
    at /home/yeongjet/project/wine-portal-backend/node_modules/ts-sql-query/queryBuilders/SelectQueryBuilder.js:117:60
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    ... 2 lines matching cause stack trace ...
    at async Object.addStandardWine (/home/yeongjet/project/wine-portal-backend/src/application/service/wine.service.ts:12:9)
```

**Comment by juanluispaz** [comment]
Hi, please, can you provide more details; I need:
- Full error string representation when you write using console.log
- Typescript code of the query you was trying to execute 

Thanks!

**Comment by yeongjet** [comment]
Updated. @juanluispaz

**Comment by yeongjet** [comment]
I should use `executeSelectNoneOrOne`? waste your time, sorry.

**Comment by juanluispaz** [comment]
You have several options to execute a query:

- `executeSelectOne(): Promise<RESULT>`: Execute the select query that returns one result from the database. If no result is returned by the database an exception will be thrown.
- `executeSelectNoneOrOne(): Promise<RESULT | null>`: Execute the select query that returns one or no result from the database. 

What you are looking for is `executeSelectNoneOrOne`, which will return you the empty

See https://ts-sql-query.readthedocs.io/en/stable/queries/basic-query-structure/#other-options for more details
