### ISSUE TITLE
sqrt error

### ISSUE THREAD

**Issue by mkupriichuk** [juanluispaz/ts-sql-query#73]
Hello
I try to get ```sqrt``` from number:

```outlier: scoreProductWeekdayHour.outlier.sqrt()```

But as result query we get ```sqTr``` not ```sqRt```

```select sqtr(outlier) as outlier from sa_score_product_weekday_hour_u```

```ts-sql-query``` version ```1.41.0```

**Comment by juanluispaz** [comment]
Fixed in ts-sql-query 1.48.0 already published
