### ISSUE TITLE
ts error - Property '[database]' is missing in type

### ISSUE THREAD

**Issue by kir4ik** [juanluispaz/ts-sql-query#79]
Hi, i got a ts error ```Property '[database]' is missing in type``` when trying to use `InsertableValues` or `MandatoryInsertSets`

```ts
class SomeTable extends Table<Connection, 'SomeTable'> {
  id = this.primaryKey('id', 'string');
  name = this.optionalColumn('name', 'string');

  constructor() {
    super('some_table');
  }
}

type A = RequiredColumnsForSetOf<SomeTable>;
type B = OptionalColumnsForSetOf<SomeTable>;
```

the following values are displayed for type A and B
```ts
type A = typeof database | "id";
type A = typeof database | "name";
```

expected
```ts
type A = "id";
type A = "name";
```

ts gives an error
```Property '[database]' is missing in type```

if you try to use the `values` method

```ts
connection.insertInto(someTable).values([{id: '1', name: 'test'}]);
```

or

```ts
const someRecord: InsertableValues<SomeTable> = {
  id: '1',
  name: 'test'
};
```

---
I think, in the following definitions - expression must be used `keyof T & string` instead `keyof T`
```
export declare type RequiredColumnsForSetOf
export declare type OptionalColumnsForSetOf
```

**Comment by juanluispaz** [comment]
Hi, 

Please, do not use internal ts-sql-query's types; I cannot warranty that I don't break them when I update versions or they work as you expect.

The types you are looking for are documented here: https://ts-sql-query.readthedocs.io/en/stable/advanced-usage/#utility-types

**Comment by kir4ik** [comment]
sorry, vscode showed this error
this error disappeared after restarting vscode
