### ISSUE TITLE
how build insert/update query for mysql with native mysql expressions

### ISSUE THREAD

**Issue by kir4ik** [juanluispaz/ts-sql-query#81]
Hi,
how can i execute similar expression to insert or update data? (for `MySql`)

```ts
const value = '2023-02-08T19:11:12.485Z';

const someInsertQuery = connection.insert(someTable).values({
 timestamp: FROM_UNIXTIME(${new Date(value).getTime() / 1000})
})
```

I want to receive this request
```sql
INSERT INTO `someTable` (`timestamp`) VALUES(FROM_UNIXTIME(1675883472.485))
```

Maybe I can make my own `TimestampTypeAdapter` , but how do I describe this as a result of transformValueToDB?

**Comment by juanluispaz** [comment]
Hi, 

There are several ways to interpret what you are writing; I'm not sure which one is the one you are looking for; then I will express what I have in my mind:

1. If you need to write a custom sql fragment like `FROM_UNIXTIME(...)` use [sql fragments](https://ts-sql-query.readthedocs.io/en/stable/queries/sql-fragments/); you can even create a reusable function that builds the fragment

2. You need to have a custom type, your own date representation, different from what is returned by the database; then, you will need to use a type adapter or define it globally in your connection:

```ts
class DBConnection extends MySqlConnection<'DBConnection'> { 

    protected transformValueFromDB(value: unknown, type: string): unknown {
        if (value && type === 'MyCustomDateTime') {
            if (typeof value !== 'string') {
                throw new Error('Invalid MyCustomDateTime value comming from the DB')
            }
            return value // Not sure if any transformation is required
        }
        return super.transformValueFromDB(value, type)
    }

    protected transformValueToDB(value: unknown, type: string): unknown {
        if (value && type === 'MyCustomDateTime') {
            if (typeof value !== 'string') {
                throw new Error('Invalid MyCustomDateTime value to send to the DB')
            }
            return new Date(value).getTime() / 1000
        }
        return super.transformValueToDB(value, type)
    }

    protected transformPlaceholder(placeholder: string, type: string, forceTypeCast: boolean, valueSentToDB: unknown): string {
        if (valueSentToDB && type === 'MyCustomDateTime') {
            // In case of null, don't add the cast
            return 'FROM_UNIXTIME(' + placeholder + ')'
        }
        return super.transformPlaceholder(placeholder, type, forceTypeCast, valueSentToDB)
    }
}
```

And you create your columns as:

```ts
const tCustomer = new class TCustomer extends Table<DBConnection, 'TCustomer'> {
    id = this.autogeneratedPrimaryKey('id', 'int')
    firstName = this.column('first_name', 'string')
    lastName = this.column('last_name', 'string')
    birthday = this.optionalColumn('birthday', 'customComparable', 'MyCustomDateTime')
    constructor() {
        super('customer');
    }
}()
```

Note: the same methods included in the connection exist as well as type adapter

Read more here: https://ts-sql-query.readthedocs.io/en/stable/column-types/#type-adapters

3. If you are having timezone issues, a good practice, when it is possible, is to ensure your Node server and your database are in the same timezone, UTC-0 preferably; if that is not possible, some database connectors allow you to deals with timezone corrections when both servers are not in the same timezone. Note: ensure you are not connecting to MariaDB using a MySql connector.

- In mariadb connector, you have some options: https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#timezone-consideration

- mysql and mysql2 have a property called 'timezone' in the connection object to control this issue: https://github.com/mysqljs/mysql#connection-options

Let me know if this helps you.

**Comment by kir4ik** [comment]
first case works
but in the second case, the `transformPlaceholder` method with adapters doesn't work, is not called

**Comment by kir4ik** [comment]
Thanks

updated the version from 1.38 to the latest, now there is a transformPlaceholder method, added it to my TimestampTypeAdapter and it works
